// Generated by npm run puzzlegen (seed 20260715). Do not edit by hand.
import type { Puzzle } from './types'

export const GENERATED_PUZZLES: ReadonlyArray<Puzzle> = [
  {
    "id": "generated-rule-1-01",
    "mode": "rule",
    "board": "-------------------b-------bb------bw---------------------------",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-02",
    "mode": "rule",
    "board": "-------------------bw------bb------bbb--------------------------",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-03",
    "mode": "rule",
    "board": "bbbbwww-bbwwwwbbbbbbwbwbbwbbwwbbbbwwbbbbbbbbbbbbbbwwwbwbbbbbbbbb",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-04",
    "mode": "rule",
    "board": "bw-wwwwbbbbbbww-bwbbwwwwbwbwbwwwbwbbbwww-wbbwwwwbb-wbwwwbbbb-www",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-05",
    "mode": "rule",
    "board": "bwwwwwwbbbbwbbbbbwbbwwbwbwbwbbwwbwbbbwww-bwbwwwwbbbwwwwwbbbbwwww",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-06",
    "mode": "rule",
    "board": "---------------------------wb------bb-------b-------------------",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-07",
    "mode": "rule",
    "board": "wbw-bbb-wwwwwbbbwbbbbwbbwbbwbbbbwbwwwwbb-wwwwbbb-wwbwwbb-bbbbbbb",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-08",
    "mode": "rule",
    "board": "--------------------------bbb------bw---------------------------",
    "turn": "w",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-09",
    "mode": "rule",
    "board": "wbbbbbbw-bwbbbb--wbbbwbww-bbwwbw--bbbwbw--bbbbww-----bbw---www--",
    "turn": "b",
    "difficulty": 1
  },
  {
    "id": "generated-rule-1-10",
    "mode": "rule",
    "board": "wwww---bwbbbbbb-wbwwwwwwwwbbbbb-wbbbbbb-wbbbb-----b-b-----b-----",
    "turn": "b",
    "difficulty": 1
  },
  {
    "id": "generated-rule-2-01",
    "mode": "rule",
    "board": "---------------------------wb------bw---------------------------",
    "turn": "b",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-02",
    "mode": "rule",
    "board": "-------------------bw------bw------bw---------------------------",
    "turn": "b",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-03",
    "mode": "rule",
    "board": "------------------www------bb------bbb--------------------------",
    "turn": "b",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-04",
    "mode": "rule",
    "board": "-----------b------wbw------bb------bbb--------------------------",
    "turn": "w",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-05",
    "mode": "rule",
    "board": "--w--------w-bb---wwbb---wwbbw---bbbbw----bbbw---w-b-w----------",
    "turn": "w",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-06",
    "mode": "rule",
    "board": "--w--------w-bb---wwbb---wwbbw--wwwwww----bbbw---w-b-w----------",
    "turn": "b",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-07",
    "mode": "rule",
    "board": "--wb-------b-bb---wbbb---wwbbw--wwwwww----bbbw---w-b-w----------",
    "turn": "w",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-08",
    "mode": "rule",
    "board": "--wb-------b-bb---wbbb---wwbbw--wwwwww----bwbw---w-w-w-----w----",
    "turn": "b",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-09",
    "mode": "rule",
    "board": "-bbb-bw--wwwbbbbwwwbwbbbwwbwwbb-wbwwbbb-bbbbbb--bbwwwww-bbbbbb--",
    "turn": "w",
    "difficulty": 2
  },
  {
    "id": "generated-rule-2-10",
    "mode": "rule",
    "board": "bbbb-bw--bwwbbbbwwbbwbbbwwbbwwb-wbwwbbw-bbbbbb-wbbwwwww-bbbbbb--",
    "turn": "w",
    "difficulty": 2
  },
  {
    "id": "generated-rule-3-01",
    "mode": "rule",
    "board": "-----------b------wbw-----bww-----bwwb----bbw------b-w----------",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-02",
    "mode": "rule",
    "board": "-----------b------wbb-----bbbb----bwbb----wbbb---w-b-w----------",
    "turn": "w",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-03",
    "mode": "rule",
    "board": "-----------b--b---wwwb---wwwbw---bbbbw----bbbw---w-b-w----------",
    "turn": "w",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-04",
    "mode": "rule",
    "board": "--w--------w--b---wwwb---wwwbw---bbbbw----bbbw---w-b-w----------",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-05",
    "mode": "rule",
    "board": "--wb-------b-bb---wbbb---wwbbw--wwwwww----bwww---w-bww-----wb---",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-06",
    "mode": "rule",
    "board": "--wb------wb-bb---wwbb---wwbwb--wwwwwwb---wwwb---wwwbw----bbb---",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-07",
    "mode": "rule",
    "board": "--wb------wwwbb---wwwb---wwbwb--wwwwbwb---wbwb---wbwbw---bbbb---",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-08",
    "mode": "rule",
    "board": "--wb--w---bwwwb--bbbwb---wwwwb--wwwwbwb---wbwb---wbwbw---bbbb---",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-09",
    "mode": "rule",
    "board": "-bbb-bw--wwwbbwb-wwbwbw-bwwwwbw-wbwwbbb---bbwb--wwwwwww-bbbbbb--",
    "turn": "w",
    "difficulty": 3
  },
  {
    "id": "generated-rule-3-10",
    "mode": "rule",
    "board": "-bbb-bw--wwwbbwbwwwbwbw-wwwwwbw-wbwwbbb---bbwb--wwwwwww-bbbbbb--",
    "turn": "b",
    "difficulty": 3
  },
  {
    "id": "generated-corner-01",
    "mode": "strategy",
    "category": "corner",
    "board": "-----------b------wbb-----bbbb----bwbb----wbw----w-b-w----------",
    "turn": "b",
    "answers": [
      56
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-02",
    "mode": "strategy",
    "category": "corner",
    "board": "-----------b------wwww---wwwww---bbwbw----bbbw---w-b-w----------",
    "turn": "b",
    "answers": [
      56
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-03",
    "mode": "strategy",
    "category": "corner",
    "board": "--wb-------b-bb---wbbb---wwbbw--wwwwww----wwww---wwwww----bbb---",
    "turn": "b",
    "answers": [
      56
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-04",
    "mode": "strategy",
    "category": "corner",
    "board": "--wb-------b-bb---wbbb---wwbbb--wwwwwwb---wwwb---wwwbw----bbb---",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-05",
    "mode": "strategy",
    "category": "corner",
    "board": "--wb------wb-bb---wwbb---wwbwb--wwwwbwb---wbwb---wbwbw---bbbb---",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-06",
    "mode": "strategy",
    "category": "corner",
    "board": "--wb------bwwbb--bbbbb---wwbwb--wwwwbwb---wbwb---wbwbw---bbbb---",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-07",
    "mode": "strategy",
    "category": "corner",
    "board": "-bbb--w---bwwwb--bbbwb---wwwwb--wwwwbwb---wbwb---wbwbw---bbbb---",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-08",
    "mode": "strategy",
    "category": "corner",
    "board": "-bbb--w---bwwww--bbbwww--wwwww--wwwwwbb---wbwb---wbwbbw--bbbbb--",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-09",
    "mode": "strategy",
    "category": "corner",
    "board": "-bbb--w--wwwwww--wwbwww-bwwwww--wbwwwbb---bbwb---wbbbbw--bbbbb--",
    "turn": "b",
    "answers": [
      0,
      7,
      56,
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-10",
    "mode": "strategy",
    "category": "corner",
    "board": "-bbb--w--wwwwww--wwbwww-bwwwww--wbwwwbb---bbwb--wwwwwww-bbbbbb--",
    "turn": "b",
    "answers": [
      0,
      7,
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-11",
    "mode": "strategy",
    "category": "corner",
    "board": "-bbb--w--wwwwwwb-wwbwww-bwwwwww-wbwwbwb---bbwb--wwwwwww-bbbbbb--",
    "turn": "b",
    "answers": [
      0,
      7,
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-12",
    "mode": "strategy",
    "category": "corner",
    "board": "bbbbwww--bwwwwbbwwbbwbwbwwbbwwwwwbwwbbw-bbbbbb-wbbwwwbb-bbbbbbbb",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-13",
    "mode": "strategy",
    "category": "corner",
    "board": "bbbbwww--bwwwwbbwwbbwbwbwwbbwwwwwbwwbbw-bbbbbb-wbbwwwwwwbbbbbbbb",
    "turn": "b",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-14",
    "mode": "strategy",
    "category": "corner",
    "board": "bbbbwww-bbwwwwbbbbbbwbwbbwbbwwwwbbwwbbw-bbbbbb-wbbwwwwwwbbbbbbbb",
    "turn": "w",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-15",
    "mode": "strategy",
    "category": "corner",
    "board": "bbbbwww-bbwwwwbbbbbbwbwbbwbbwwwwbbwwbww-bbbbbbwwbbwwwwwwbbbbbbbb",
    "turn": "b",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-16",
    "mode": "strategy",
    "category": "corner",
    "board": "---www-----b-bw--bbbbbww--bbbbw--wbbbwb----bwb-----bb------b----",
    "turn": "b",
    "answers": [
      7
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-17",
    "mode": "strategy",
    "category": "corner",
    "board": "---www-b--bw-bb-wwwwwwww-wbwwwwwbbbbbwwb---wwb-----bw-b----b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-18",
    "mode": "strategy",
    "category": "corner",
    "board": "---www-b--bw-bb-wwwbwwww-wbwbwwwbbbbbbwb---wwwb----bw-bb---b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-19",
    "mode": "strategy",
    "category": "corner",
    "board": "b--www-b-bww-bb-wwbbwwww-wbbbwwwbbbbbbwb---wwwb----bw-bb---b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-20",
    "mode": "strategy",
    "category": "corner",
    "board": "b--www-b-bww-bb-wwbbwwww-wbbbwwwbbbbbbww---wwwww---bw-wb---b-w--",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-21",
    "mode": "strategy",
    "category": "corner",
    "board": "b--www-b-bww-bb-wwbbwwwwbbbbbwwwbbbbbbww---wwwww---bw-wb---b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-22",
    "mode": "strategy",
    "category": "corner",
    "board": "b--www-b-bww-bb-wwbbwwwwbwbwbwwwbwwbbbww-w-wwwww---bw-wb---b-w--",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-23",
    "mode": "strategy",
    "category": "corner",
    "board": "b--www-bbbww-bb-bbbbwwwwbwbwbwwwbwwbbbww-w-wwwww---bw-wb---b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-24",
    "mode": "strategy",
    "category": "corner",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwbwwwbwwbbbww-w-wwwww---bw-wb---b-w--",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-25",
    "mode": "strategy",
    "category": "corner",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwbwwwbwwbbbww-w-wbbww---bbbbb---b-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-26",
    "mode": "strategy",
    "category": "corner",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwbwwwbbbbbwww-wbbbbww---wbbbb--wb-w--",
    "turn": "w",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-27",
    "mode": "strategy",
    "category": "corner",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwwwwwbwbwwwww-wwbbwwwbw-wbbww--wb-w-w",
    "turn": "b",
    "answers": [
      56
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-28",
    "mode": "strategy",
    "category": "corner",
    "board": "bw-www-bbbbbbbb-bwbbbwwwbwbwbwwwbwbwbwww-wwbwwwwbw-wbwww--wb-www",
    "turn": "b",
    "answers": [
      56
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-29",
    "mode": "strategy",
    "category": "corner",
    "board": "----------------w-wb-----wbbb-----wbwb-----wbw----w-www---------",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-corner-30",
    "mode": "strategy",
    "category": "corner",
    "board": "----------------w-wb----bbbbb-----wbwww----wbw----w-www---------",
    "turn": "b",
    "answers": [
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-01",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-----------b------wbw------bw------bwb------w-------------------",
    "turn": "b",
    "answers": [
      13,
      17,
      21,
      25,
      29,
      45,
      51,
      53
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-02",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-----------b------wbb-----bbbb----bwbb----bbw------b-w----------",
    "turn": "w",
    "answers": [
      3,
      4,
      12,
      17,
      21,
      30,
      33,
      38,
      41,
      45,
      50,
      58,
      59
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-03",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-----------b------wwww----bbww----bwbw----wbbw---w-b-w----------",
    "turn": "b",
    "answers": [
      10,
      12,
      13,
      22,
      25,
      30,
      33,
      38,
      41,
      46,
      50,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-04",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-bbb--w---bwwwb--bbbwb---wwwwb--wwwwwbb---wbwb---wbwbbw--bbbbb--",
    "turn": "w",
    "answers": [
      7,
      8,
      15,
      16,
      22,
      30,
      39,
      46,
      47,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-05",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-bbb--w---bwwww--bbbwww-bwwwww--wbwwwbb---bbwb---wbbbbw--bbbbb--",
    "turn": "w",
    "answers": [
      8,
      16,
      30,
      39,
      40,
      41,
      46,
      47,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-06",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "----bw-----b-b----bbbbb---wbw-b--wbbbbb----bbb-----b------------",
    "turn": "w",
    "answers": [
      3,
      10,
      12,
      29,
      39,
      42,
      46,
      52,
      53
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-07",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "----bw-----b-b----bbbbb---wbw-b--wbbwbb----bwb-----bb------b----",
    "turn": "w",
    "answers": [
      3,
      10,
      12,
      23,
      29,
      39,
      42,
      46,
      50,
      58,
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-08",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "---www-----b-b---bbbbbbw--bbbbw--wbbbwb----bwb-----bb------b----",
    "turn": "w",
    "answers": [
      8,
      10,
      12,
      16,
      25,
      31,
      39,
      42,
      46,
      53,
      58,
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-09",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "---www-b--bw-bb--bbbbbww-wbwwww--wbbbwb----bwb-----bb------b----",
    "turn": "w",
    "answers": [
      1,
      6,
      8,
      12,
      16,
      24,
      39,
      41,
      42,
      46,
      47,
      50,
      53,
      58,
      60,
      61
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-10",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "---www-b--bw-bb--bbbbbww-wbwwwb--wwbbwbb---wwb-----bw------b-w--",
    "turn": "w",
    "answers": [
      1,
      2,
      6,
      8,
      12,
      16,
      24,
      31,
      42,
      46,
      47,
      50,
      53,
      58
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-11",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "---www-b--bw-bb-wwwwwwww-wbwwwwwbbbbbwwb---www-----bw------b-w--",
    "turn": "b",
    "answers": [
      8,
      12,
      15,
      24,
      46,
      50,
      53,
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-12",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "---www-b--bw-bb-wwwwwwww-wbwwwwwbbbbbwwb---wwww----bw-b----b-w--",
    "turn": "b",
    "answers": [
      8,
      12,
      15,
      24,
      50,
      53,
      55,
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-13",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwbwwwbbbbwwww-wbbbwww---wbbww--wb-w-w",
    "turn": "b",
    "answers": [
      2,
      12,
      15,
      40,
      48,
      50,
      57,
      60,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-14",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "bw-www-bbwww-bb-bwbbwwwwbwbwbwwwbbbbwwww-bbbbwwwb--wbbww--wb-w-w",
    "turn": "w",
    "answers": [
      6,
      40,
      50,
      60,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-15",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--------------------------bbb------bw-------bw------wb----------",
    "turn": "w",
    "answers": [
      18,
      20,
      34,
      43,
      61
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-16",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--------------------------bbb-----wbw------bbw------wb----------",
    "turn": "w",
    "answers": [
      18,
      20,
      42,
      50,
      61
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-17",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "------------------wb------wbb-----wbw------bbw------wb----------",
    "turn": "w",
    "answers": [
      12,
      20,
      29,
      42,
      50,
      61,
      62
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-18",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "------------------wb------wbb-----wbw------wbw----w-wb----------",
    "turn": "b",
    "answers": [
      17,
      25,
      33,
      37,
      41,
      42,
      46,
      51,
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-19",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-----------b----wwwww---bbwbw-----wwwww----www----wwwww-----b-b-",
    "turn": "b",
    "answers": [
      8,
      10,
      12,
      13,
      29,
      41,
      42,
      46,
      59,
      61,
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-20",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "-----------b----wwwww---bbwbw-----wwwww---wwww----wbwww----bb-b-",
    "turn": "b",
    "answers": [
      8,
      10,
      12,
      13,
      29,
      30,
      31,
      33,
      41,
      46,
      55,
      61,
      63
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-21",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--w-----b--w----bbwwww--bbbbwb----wwbbw---wwbb----wbwbww---bb-bb",
    "turn": "b",
    "answers": [
      3,
      4,
      10,
      12,
      13,
      22,
      31,
      33,
      39,
      41,
      46,
      47,
      57,
      58,
      61
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-22",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--w-----bb-w----bbbwww--bbbbww----wwbww---wwbw----wbwwww---bbwbb",
    "turn": "b",
    "answers": [
      3,
      4,
      12,
      13,
      22,
      30,
      31,
      33,
      39,
      41,
      46,
      47,
      57,
      58
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-23",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--w-----bb-w-w--bbbbwwb-bbbwww----wwbww---wwbw----wbwwww---bbwbb",
    "turn": "b",
    "answers": [
      3,
      4,
      12,
      30,
      31,
      33,
      39,
      41,
      46,
      47,
      57,
      58
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-24",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "--w-----bb-w-w--bbbbwwb-bbbwbw----wwbbw---wwbbb---wbwbbw--wwwwbb",
    "turn": "b",
    "answers": [
      3,
      4,
      5,
      12,
      30,
      31,
      33,
      39,
      41,
      47,
      57
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-25",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "w-w-----bw-w-w--bbwbwwb-bbbwbbb---wwbbb---wwbbb---wbwbbw--wwwwbb",
    "turn": "b",
    "answers": [
      1,
      3,
      4,
      5,
      10,
      12,
      33,
      41,
      47,
      57
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-26",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "w-w-----bw-w-w--bbwbwwb-bbbwbbb---wwbbb---wbbbb---bbwbbw-bbbbbbb",
    "turn": "w",
    "answers": [
      10,
      23,
      31,
      32,
      33,
      39,
      47
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-27",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "w-w-----bw-w-w--bbwbwwb-bbbwbwb---wwbbw---wwwwww--bbwbbw-bbbbbbb",
    "turn": "b",
    "answers": [
      1,
      3,
      4,
      5,
      10,
      12,
      31,
      33,
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-28",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "wbw-----bb-w-w--bbwbwwb-bbbwbwb---wwbbw---wwwwww--bbwbbw-bbbbbbb",
    "turn": "w",
    "answers": [
      10,
      15,
      23,
      31,
      32,
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-29",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "wbw-----wb-w-w--wbwbwwb-wwbwbwb-w-wwbbw---wwwwww--bbwbbw-bbbbbbb",
    "turn": "b",
    "answers": [
      3,
      4,
      5,
      10,
      12,
      31,
      33,
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-avoid-x-30",
    "mode": "strategy",
    "category": "avoid-x",
    "board": "wbw-----wb-w-w--wbwbwwb-wwbwbwbbw-wwbbb---wwwbww--bbbbbw-bbbbbbb",
    "turn": "w",
    "answers": [
      10,
      15,
      23,
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-01",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-----------b------wbw------bw------bwb------b------b------------",
    "turn": "w",
    "answers": [
      26
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-02",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-----------b------wbw-----bww-----bwwb----bbb------b------------",
    "turn": "w",
    "answers": [
      3
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-03",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-bbb--w--wwwwww--wwbwww-bwwwww--wbwwwbb---bbwb---bbbbbw-bbbbbb--",
    "turn": "w",
    "answers": [
      16
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-04",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------------bw-----www-----bwbb-----wwb------------------",
    "turn": "b",
    "answers": [
      51
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-05",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "----bw-----b-b----bbbbb---wbw-b--wbbwbb----bwb-----bw-----------",
    "turn": "b",
    "answers": [
      60
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-06",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---www-----b-b----bbbbb---wbw-b--wbbwbb----bwb-----bb------b----",
    "turn": "b",
    "answers": [
      29
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-07",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---www-b---b-bb--bbbbbww--bbbbw--wbbbwb----bwb-----bb------b----",
    "turn": "w",
    "answers": [
      12
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-08",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---www-b--bw-bb-wwwwwwww-wbwwwb-bbbbbwbb---wwb-----bw------b-w--",
    "turn": "w",
    "answers": [
      54
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-09",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------------------------wb------bw-------bw------------------",
    "turn": "b",
    "answers": [
      37
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-10",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "----------------w-wb----bbbbb-----wbwww----wbw----w-bww-----b---",
    "turn": "w",
    "answers": [
      11
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-11",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-----------b----w-bbw---bbbbw-----wbwww----www----wwwww-----b-b-",
    "turn": "w",
    "answers": [
      3
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-12",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "--w--------w----wwwww---bbwbbb----wwbbw---wwwb----wbwwww---bb-bb",
    "turn": "b",
    "answers": [
      8
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-13",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "--w-----bb-w----bbbbbbb-bbbbwb----wwbww---wwbw----wbwwww---bbwbb",
    "turn": "w",
    "answers": [
      58
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-14",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "wbw-----wb-w-w--wbwbwwwwwwbwbwwbw-wwbwb---wwwbww--bbbbbw-bbbbbbb",
    "turn": "b",
    "answers": [
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-15",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "wbw-----wbbw-w--wbbbwwwwwwbwbwwbw-wwbwb---wwwbww-wwwwwww-bbbbbbb",
    "turn": "b",
    "answers": [
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-16",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "wbw-bb--wbbbbb-bwbbbbwbbwbbwbbwbwbwwwwwb-wwwwbwb-wwbwwwb-bbbbbbb",
    "turn": "w",
    "answers": [
      3
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-17",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------------b-w-----bw-----bww----b----------------------",
    "turn": "b",
    "answers": [
      37
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-18",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------------b-w----wwww----bbbw---b-b--------------------",
    "turn": "b",
    "answers": [
      18
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-19",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------------b-www--wwwb----bbbw---b-b--------------------",
    "turn": "b",
    "answers": [
      25
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-20",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "------------------bb-www-wwwwb----bbbw---b-b--------------------",
    "turn": "b",
    "answers": [
      24
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-21",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------b----bb-bww-wwwwb----bbbw---b-b--------------------",
    "turn": "w",
    "answers": [
      5
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-22",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-------------b----bbwwww-wwwwb----bbbw---b-b--------------------",
    "turn": "b",
    "answers": [
      24
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-23",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------w--bb----wbbwww-wwwbb----bbbw---b-b--------------------",
    "turn": "b",
    "answers": [
      24
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-24",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "-----www-w--bb-bwbbbbbbwwwbbbbb-w-wbbbbbbbbb--w-www-------------",
    "turn": "w",
    "answers": [
      31
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-25",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "------------------w-------bwb------bw---------------------------",
    "turn": "b",
    "answers": [
      19
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-26",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------b--------b-------bbbw-----bwww----wb-------------------",
    "turn": "b",
    "answers": [
      39
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-27",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------b--------b-------bbbw-----bbww----wbb------------------",
    "turn": "w",
    "answers": [
      34
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-28",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------b-------wb-------wbbbb----wbww----wwww-----------------",
    "turn": "b",
    "answers": [
      25
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-29",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "---------b-------wb-------wbbbb----bbwb--wwwwwwb----------------",
    "turn": "w",
    "answers": [
      19
    ],
    "difficulty": 1
  },
  {
    "id": "generated-min-mobility-30",
    "mode": "strategy",
    "category": "min-mobility",
    "board": "w--------w-------ww-------wwbbb----bwwb--wwwwwwb----------------",
    "turn": "b",
    "answers": [
      55
    ],
    "difficulty": 1
  }
]
