import type { StrategyPuzzle } from './types'

export const SAMPLE_STRATEGY_PUZZLES: ReadonlyArray<StrategyPuzzle> = [
  {
    id: 'corner-one',
    mode: 'strategy',
    category: 'corner',
    board: '----------b------wb-w----bwbw-----bwb----bbb-b---bbb-----b------',
    turn: 'w',
    answers: [56],
    difficulty: 1,
  },
  {
    id: 'corner-two',
    mode: 'strategy',
    category: 'corner',
    board: '--bw-----wb------wwbw----bbwbb--wwwwwb---bbbbb--bbbbw---wb--w---',
    turn: 'b',
    answers: [0],
    difficulty: 1,
  },
  {
    id: 'corner-three',
    mode: 'strategy',
    category: 'corner',
    board: '--bw-----wb------bwbw---bbbwbb--wbwwwb---bbbwb--bbbbww--wb--w---',
    turn: 'b',
    answers: [0],
    difficulty: 1,
  },
  {
    id: 'avoid-x-one',
    mode: 'strategy',
    category: 'avoid-x',
    board: '----------b------wb-w----bwww-----bww-----bb------bb-----b------',
    turn: 'b',
    answers: [13, 16, 19, 21, 24, 29, 37, 45],
    difficulty: 1,
  },
  {
    id: 'avoid-x-two',
    mode: 'strategy',
    category: 'avoid-x',
    board: '---w------w------wwww----bbbwb---bbww----bbbwb--bbbbw---wb--w---',
    turn: 'b',
    answers: [2, 8, 11, 12, 13, 21, 37, 53, 59, 61],
    difficulty: 1,
  },
  {
    id: 'avoid-x-three',
    mode: 'strategy',
    category: 'avoid-x',
    board: '--bw------b------wbww----bbbwb---bbww----bbbwb--bbbbw---wb--w---',
    turn: 'w',
    answers: [1, 16, 22, 24, 30, 32, 38, 40, 46, 58, 59],
    difficulty: 1,
  },
  {
    id: 'min-mobility-one',
    mode: 'strategy',
    category: 'min-mobility',
    board: '--------------------------bbb-----wbw------w------w-------------',
    turn: 'b',
    answers: [51],
    difficulty: 1,
  },
  {
    id: 'min-mobility-two',
    mode: 'strategy',
    category: 'min-mobility',
    board: '--------------------------bbb-----wbw------b------wb------------',
    turn: 'w',
    answers: [52],
    difficulty: 1,
  },
  {
    id: 'min-mobility-three',
    mode: 'strategy',
    category: 'min-mobility',
    board: '------------------w-------wwb-----wbw------b------bb-----b------',
    turn: 'w',
    answers: [59],
    difficulty: 1,
  },
]
